Fix a build breakage on MacOS (#1955)
Without this change, the following error occurs on MacOS (but not linux):

  ../core/indexing/chunk/ChunkCodebaseIndex.ts:175:5 - error TS2322: Type 'unknown[]' is not assignable to type 'Chunk[]'.
    Type '{}' is missing the following properties from type 'Chunk': digest, filepath, index, content, and 2 more.

  175     return chunkLists.flat();
          ~~~~~~~~~~~~~~~~~~~~~~~~~

Co-authored-by: Rob Leidle <rleidle@tesla.com>